/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NewUsersPermissionsRole
 */
export interface NewUsersPermissionsRole {
    /**
     * 
     * @type {string}
     * @memberof NewUsersPermissionsRole
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof NewUsersPermissionsRole
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof NewUsersPermissionsRole
     */
    type?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof NewUsersPermissionsRole
     */
    permissions?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof NewUsersPermissionsRole
     */
    users?: any;
    /**
     * 
     * @type {string}
     * @memberof NewUsersPermissionsRole
     */
    createdBy?: any;
    /**
     * 
     * @type {string}
     * @memberof NewUsersPermissionsRole
     */
    updatedBy?: any;
}
