/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Posts
 */
export interface Posts {
    /**
     * 
     * @type {string}
     * @memberof Posts
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof Posts
     */
    title?: any;
    /**
     * 
     * @type {string}
     * @memberof Posts
     */
    content?: any;
    /**
     * 
     * @type {Date}
     * @memberof Posts
     */
    publishedAt?: any;
}
