/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UsersPermissionsUser
 */
export interface UsersPermissionsUser {
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUser
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUser
     */
    username: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUser
     */
    email: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUser
     */
    provider?: any;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsUser
     */
    confirmed?: any;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsUser
     */
    blocked?: any;
    /**
     * 
     * @type {UsersPermissionsUserRole}
     * @memberof UsersPermissionsUser
     */
    role?: any;
}
