/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UsersPermissionsRoleUsers
 */
export interface UsersPermissionsRoleUsers {
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRoleUsers
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRoleUsers
     */
    username: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRoleUsers
     */
    email: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRoleUsers
     */
    provider?: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRoleUsers
     */
    password?: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRoleUsers
     */
    resetPasswordToken?: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRoleUsers
     */
    confirmationToken?: any;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsRoleUsers
     */
    confirmed?: any;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsRoleUsers
     */
    blocked?: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRoleUsers
     */
    role?: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRoleUsers
     */
    createdBy?: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRoleUsers
     */
    updatedBy?: any;
}
