/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UsersPermissionsRole
 */
export interface UsersPermissionsRole {
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRole
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRole
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRole
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRole
     */
    type?: any;
    /**
     * 
     * @type {Array&lt;UsersPermissionsRolePermissions&gt;}
     * @memberof UsersPermissionsRole
     */
    permissions?: any;
    /**
     * 
     * @type {Array&lt;UsersPermissionsRoleUsers&gt;}
     * @memberof UsersPermissionsRole
     */
    users?: any;
}
