/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UsersPermissionsRolePermissions
 */
export interface UsersPermissionsRolePermissions {
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRolePermissions
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRolePermissions
     */
    type: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRolePermissions
     */
    controller: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRolePermissions
     */
    action: any;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsRolePermissions
     */
    enabled: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRolePermissions
     */
    policy?: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRolePermissions
     */
    role?: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRolePermissions
     */
    createdBy?: any;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRolePermissions
     */
    updatedBy?: any;
}
